name: app_flutter
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.4
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.2
  firebase_analytics: ^11.4.2
  intl: ^0.20.2
  flutter_local_notifications: ^18.0.0
  timezone: ^0.10.0
  permission_handler: ^11.4.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/medicine_medical.png"
  min_sdk_android: 21
  
flutter_native_splash:
  color: "#66BB6A"
  image: assets/images/background_splash.png
  branding: assets/images/background_splash.png
  color_dark: "#66BB6A"
  image_dark: assets/images/background_splash.png
  branding_dark: assets/images/background_splash.png
  ios: true
  android_12:
    image: assets/images/background_splash.png
    icon_background_color: "#66BB6A"
    image_dark: assets/images/background_splash.png
    icon_background_color_dark: "#66BB6A"

flutter:
  uses-material-design: true
  assets: 
     - assets/images/
     - assets/images/medicine_medical.png
     - assets/images/background_splash.png

     
